Bn128
runtimeverification/bn128-ml pull request #1
Opened 2017-09-14 17:42 UTC by dwightguth

2017-09-14 17:48 UTC, bmmoore requested changes
I don't know if the algorithm is correct, but the code and API looks reasonable.

Considering there was already a bug to fix, I think the project needs at least one or two test vectors.

2017-09-14 20:08 UTC, dwightguth commented
@bmmoore please re-review

2017-09-20 18:00 UTC, bmmoore approved these changes

2017-09-20 18:00 UTC, merged

2017-09-20 18:00 UTC, bmmoore commented
Did you come up with these tests yourself, or take them from some source? I'm not sure how comprehensive they are.